name: Deploy to Self-hosted Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKER_IMAGE: ${{ vars.APP_NAME }}
      CONTAINER_NAME: ${{ vars.APP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Stop and remove old Docker container
        run: |
          # Check if container exists and is running
          if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            echo "Stopping and removing existing container..."
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
          else
            echo "No existing container found"
          fi

      - name: Run Docker container and create credentials
        run: |
          # 首先启动容器
          docker run -d \
            --name ${{ env.CONTAINER_NAME }} \
            --restart unless-stopped \
            -v /root/data/${{ env.CONTAINER_NAME }}:/app/data \
            -e APP_NAME=${{ vars.APP_NAME }} \
            -e SAVE_CREDENTIALS=true \
            -p 8009:8009 \
            --cpus="0.30" \
            ${{ env.DOCKER_IMAGE }}
          
          # 等待容器完全启动
          sleep 5
          
          # 在容器内创建 credentials.json，使用 printf 来确保正确处理 JSON
          docker exec ${{ env.CONTAINER_NAME }} /bin/sh -c 'printf "%s" "${{ secrets.GOOGLE_CLIENT_CONFIG }}" > /app/credentials.json'

      - name: Verify container is running
        run: |
            sleep 10
            if [ "$(docker ps -q -f name=${{ env.CONTAINER_NAME }})" ]; then
                echo "Container is running"
                # 验证 credentials.json 是否创建成功
                docker exec ${{ env.CONTAINER_NAME }} test -f /app/credentials.json && echo "credentials.json created successfully" || echo "Failed to create credentials.json"
            else
                echo "Container failed to start"
                exit 1
            fi

      - name: Verify credentials file
        run: |
          echo "Checking credentials.json format:"
          docker exec ${{ env.CONTAINER_NAME }} cat /app/credentials.json | python -m json.tool || echo "Invalid JSON format"