name: Deploy to Self-hosted Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKER_IMAGE: ${{ vars.BOT_NAME }}
      CONTAINER_NAME: ${{ vars.BOT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .

      - name: Stop and remove old Docker container
        run: |
          # Check if container exists and is running
          if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            echo "Stopping and removing existing container..."
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
          else
            echo "No existing container found"
          fi

      - name: Run Docker container
        run: |
          docker run -d \
            --name ${{ env.CONTAINER_NAME }} \
            --restart unless-stopped \
            -v /root/data/${{ env.CONTAINER_NAME }}:/app/data \
            -e BOT_NAME=${{ vars.BOT_NAME }} \
            -e GOOGLE_CLIENT_CONFIG=${{ secrets.GOOGLE_CLIENT_CONFIG }} \
            -p 8009:8009 \
            --cpus="0.30" \
            ${{ env.DOCKER_IMAGE }}
      - name: Verify container is running
        run: |
            sleep 10
            if [ "$(docker ps -q -f name=${{ env.CONTAINER_NAME }})" ]; then
                echo "Container is running"
            else
                echo "Container failed to start"
                exit 1
            fi