name: Deploy to Self-hosted Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 在构建 Docker 镜像之前设置凭据
      - name: Set up credentials
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          echo "{\"installed\":{\"client_id\":\"$GOOGLE_CLIENT_ID\",\"project_id\":\"$GOOGLE_PROJECT_ID\",\"auth_uri\":\"https://accounts.google.com/o/oauth2/auth\",\"token_uri\":\"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\":\"https://www.googleapis.com/oauth2/v1/certs\",\"client_secret\":\"$GOOGLE_CLIENT_SECRET\",\"redirect_uris\":[\"http://localhost\"]}}" > credentials.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        env:
          DOCKER_IMAGE: ${{ vars.BOT_NAME }}:latest
        run: |
          if [ -z "$DOCKER_IMAGE" ]; then
            echo "Error: DOCKER_IMAGE is not set. Please set the BOT_NAME repository variable."
            exit 1
          fi
          docker build -t ${DOCKER_IMAGE} .

      - name: Stop and remove old Docker container
        env:
          CONTAINER_NAME: ${{ vars.BOT_NAME }}
        run: |
          if [ -z "$CONTAINER_NAME" ]; then
            echo "Error: CONTAINER_NAME is not set. Please set the BOT_NAME repository variable."
            exit 1
          fi
          # Check if container exists and is running
          if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            echo "Stopping and removing existing container..."
            docker stop ${CONTAINER_NAME} || true
            docker rm ${CONTAINER_NAME} || true
          else
            echo "No existing container found"
          fi

      - name: Run Docker container
        env:
          DOCKER_IMAGE: ${{ vars.BOT_NAME }}:latest
          CONTAINER_NAME: ${{ vars.BOT_NAME }}
        run: |
          if [ -z "$CONTAINER_NAME" ] || [ -z "$DOCKER_IMAGE" ]; then
            echo "Error: Required variables are not set. Please set the BOT_NAME repository variable."
            exit 1
          fi
          docker run -d \
            --name ${CONTAINER_NAME} \
            --restart unless-stopped \
            -v /root/data/${CONTAINER_NAME}:/app/data \
            -e BOT_NAME=${{ vars.BOT_NAME }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }} \
            -p 8009:8009 \
            --cpus="0.30" \
            ${DOCKER_IMAGE}

      - name: Verify container is running
        env:
          CONTAINER_NAME: ${{ vars.BOT_NAME }}
        run: |
            sleep 10
            if [ "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
                echo "Container is running"
            else
                echo "Container failed to start"
                exit 1
            fi